### ISSUE TITLE
How to configure listen address 

### ISSUE THREAD

**Issue by MexHigh** [hairyhenderson/caddyprom#12]
Is there any possibility to set the listen address in the caddyfile? I'm using caddy inside docker, which makes the prometheus module unusable for me as it only listens on localhost by default.
Thanks for the help.

**Comment by endorama** [comment]
PR #4 is about this, I guess community can help getting it merged with some testing!

**Comment by MexHigh** [comment]
Ahh, I should have looked at the PRs, thanks.
