### ISSUE TITLE
Stats per Host

### ISSUE THREAD

**Issue by viliampucik** [hairyhenderson/caddyprom#13]
Please, would there be a possibility to add metrics per _host_ like it was done in https://github.com/miekg/caddy-prometheus?

```
caddy_http_request_count_total{host, family, proto}
caddy_http_request_duration_seconds{host, family, proto}
caddy_http_response_latency_seconds{host, family, proto, status}
caddy_http_response_size_bytes{host, family, proto, status}
caddy_http_response_status_count_total{host, family, proto, status}
```

**Comment by hairyhenderson** [comment]
@viliampucik yes it's possible, but I'm focusing on putting metrics into the core Caddy - see https://github.com/caddyserver/caddy/pull/3390 for some information there.

There probably won't be per-host metrics in the initial implementation there, but please feel free to comment on that issue or the linked PR with that request!

Also note that it'll need to be a configurable setting to allow for larger deployments to not suffer from high cardinality.
