### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by fred-gb** [hairyhenderson/caddyprom#6]
Hi,

I tried to create a dockerfile with caddyprom.

```
FROM caddy:builder AS builder

RUN caddy-builder \
    github.com/hairyhenderson/caddyprom

FROM caddy:latest

COPY --from=builder /usr/bin/caddy /usr/bin/caddy
```
and my caddyfile:
```
{
    order prometheus first
}

{{ domain }} {
        reverse_proxy {{ service }}:{{ port }}
        log {
                output file /var/log/caddy/{{ domain }}.log
        }
                {
                debug
        }
}

prometheus
```

After that I use ansible with docker-compose module to build and deploy caddy. It's work for caddy.

But I don't find any metrics.

```
/ # curl localhost:9180/metrics
curl: (7) Failed to connect to localhost port 9180: Connection refused
```

Where is my mistake?

Thanks

**Comment by hairyhenderson** [comment]
@quanticware you probably need to put the `prometheus` instruction earlier in your Caddyfile:

```
{
    order prometheus first
}

prometheus

{{ domain }} {
        reverse_proxy {{ service }}:{{ port }}
        log {
                output file /var/log/caddy/{{ domain }}.log
        }
                {
                debug
        }
}
```

**Comment by fred-gb** [comment]
Thanks,

But when I put caddy like your example.
Docker didn't start, with this log;

```
{"level":"info","ts":1592980371.789323,"msg":"using provided configuration","config_file":"/etc/caddy/Caddyfile","config_adapter":"caddyfile"}
run: adapting config using caddyfile: /etc/caddy/Caddyfile:7: unrecognized directive: DOMAIN
```

And when I use my fort caddyfile. docker launch, but not prometheus.

```
2020/06/24 06:35:57 [ERROR] attempt 1: [prometheus] Obtain: [prometheus] acme: error: 400 :: POST :: https://acme-v02.api.letsencrypt.org/acme/new-order :: urn:ietf:params:acme:error:rejectedIdentifier :: Error creating new order :: Cannot issue for "prometheus": Domain name needs at least one dot, url:  - retrying in 1m0s (5.299747385s/720h0m0s elapsed)...
```

It tried to enable TLS for prometheus? 

Thanks

**Comment by hairyhenderson** [comment]
@quanticware sorry - the domain needs to be first there too... Can you try the sample Caddyfile as a starter to see if that works?

Something like:

```
{
    order prometheus first
}

localhost

prometheus
```

**Comment by fred-gb** [comment]
Touch & Go at my workshop to test this, and it's work:

```
/ # netstat -lpn
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        0      0 127.0.0.1:9180          0.0.0.0:*               LISTEN      1/caddy
tcp        0      0 127.0.0.11:43805        0.0.0.0:*               LISTEN      -
tcp        0      0 127.0.0.1:2019          0.0.0.0:*               LISTEN      1/caddy
tcp        0      0 :::80                   :::*                    LISTEN      1/caddy
tcp        0      0 :::443                  :::*                    LISTEN      1/caddy
udp        0      0 127.0.0.11:38657        0.0.0.0:*                           -
```

Prometheus don't like reverseproxy?

**Comment by hairyhenderson** [comment]
@quanticware it should work with the reverse proxy, but see also #8 - it might simply be an ordering issue - I think the `prometheus` directive has to be first in order to be able to measure requests.

**Comment by fred-gb** [comment]
Sorry but after somes tries.

With file server and prometheus, it's works.
Order:
```
{
    order prometheus first
}
fileserver directive
prometheus
```

works but no prometheus with:
```
{
    order prometheus first
}
reverseproxy directive
prometheus
```

Not working docker with:
```
{
    order prometheus first
}
prometheus
reverseproxy directive

```

or:
```
{
    order prometheus first
}
prometheus
fileserver directive

```

But obviously I need reverseproxy directive with prometheus.

Thanks.

**Comment by hairyhenderson** [comment]
Have you tried something like this?

```
{
    order prometheus first
}

{{ domain }} {
        prometheus
        reverse_proxy {{ service }}:{{ port }}
        log {
                output file /var/log/caddy/{{ domain }}.log
        }
                {
                debug
        }
}
```

**Comment by francislavoie** [comment]
@quanticware Please make sure to read https://caddyserver.com/docs/caddyfile/concepts to understand the structure of the Caddyfile.

You _must_ have a site label as the first thing that isn't either a snippet or global options block. If you have more than one site, you _must_ use `{` braces to wrap your site.

If you use braces for a site block, then any directives _must_ be inside a site block. In your original Caddyfile at the top, you had `prometheus` outside the site block so it might've been parsed as a site label, not a directive.

`debug` is a global option, so it must appear on a line right before or right after the `order` global option.

`fileserver` and `reverseproxy` are not valid directives, the `_` is necessary. I.e. `file_server` and `reverse_proxy`.

It seems like you're using some templating to generate your Caddyfile? Could you please give your Caddyfile post-templating instead? It's difficult to talk about syntax specifics when we don't actually know what your template is spitting out.

**Comment by fred-gb** [comment]
Thanks @hairyhenderson It's work with this configuration.

Thanks @francislavoie, fileserver and reverseproxy are for example.

I will continue to optimize caddyfile.

**Comment by hairyhenderson** [comment]
Since it looks like it's working for you, I'll close the issue. Thanks!
